name: xrviz_env
channels:
  - conda-forge
dependencies:
  - cartopy
  - xarray
  - netcdf4
  - bokeh/label/dev::bokeh  
  - pyviz/label/dev::datashader
  - pyviz/label/dev::holoviews  
  - pyviz/label/dev::hvplot  
  - pyviz/label/dev::panel
  - pyviz/label/dev::param
  - pip:
     - "--editable=git+https://github.com/hdsingh/xrviz.git@deploy#egg=explore_xrviz"